using System;

namespace Bubbles4.Models;

public class Bookmark
{
    public required DateTime Created { get; init; }
    public required string BookPath { get; init; }
    public required int pageIndex { get; init; }
    public required bool AutoGenerated {get; init;}
}