using System;
using Bubbles4.ViewModels;
using CommunityToolkit.Mvvm.Input;

namespace Bubbles4.Models;

public partial class Bookmark : ViewModelBase
{

    public required DateTime Created { get; init; }
    public required string BookPath { get; init; }
    public required int PageIndex { get; init; }
    public required bool AutoGenerated { get; init; }
    


}